name:   github action demo
on: [push]
jobs:
  run_example_job:
    runs-on: ubuntu-latest
    steps:
        -   name: print out example job
            uses: appleboy/ssh-action@v0.1.10
            with:
                host: 18.217.252.94
                username: ec2-user
                key: ${{ secrets.SSH_KEY }}
                port: 22
                script: | 
                    echo "Nice Job!!!"